// <auto-generated />
using System;
using CustomHome.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomHome.Migrations
{
    [DbContext(typeof(ServiceStationContext))]
    [Migration("20260929160825_AddServiceTokenQueueIndex")]
    partial class AddServiceTokenQueueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CustomHome.Models.QueueSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxServing")
                        .HasColumnType("int");

                    b.Property<int>("MaxWaiting")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QueueSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxServing = 2,
                            MaxWaiting = 5
                        });
                });

            modelBuilder.Entity("CustomHome.Models.ServiceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TokenNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenNumber")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt", "Id");

                    b.ToTable("ServiceTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
